In [ ]:
import numpy as np #Làm việc với các dữ liệu mảng nhiều chiều
import pandas as pd #Giúp làm việc với các dữ liệu dạng bảng

In [4]:
high_path = "data/high_popularity_spotify_data.csv"
low_path = "data/low_popularity_spotify_data.csv"

high_df = pd.read_csv(high_path)
low_df = pd.read_csv(low_path)

print("High shape:", high_df.shape)
print("Low shape:", low_df.shape)

High shape: (1686, 29)
Low shape: (3145, 29)

In [5]:
high_df["popularity_group"] = "High"
low_df["popularity_group"] = "Low"

df = pd.concat([high_df, low_df], ignore_index=True)

print("Combined shape:", df.shape)
df.head()

Combined shape: (4831, 30)

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id,popularity_group
0,0.592,157.969,0.521,pop,-7.777,0.122,0.535,"Lady Gaga, Bruno Mars",3.0,0.0304,...,10FLjwfpbxLmW8c25Xyc2N,0.0,6.0,251668.0,0.3080,2plbrEY59IikOBgBGLjaoe,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M,High
1,0.507,104.978,0.747,pop,-10.171,0.117,0.438,Billie Eilish,4.0,0.0358,...,7aJuG4TFXa2hmE4z1yxc3n,1.0,2.0,210373.0,0.2000,6dOtVTDdiauQNBQEDOtlAB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M,High
2,0.808,108.548,0.554,pop,-4.169,0.159,0.372,Gracie Abrams,4.0,0.0368,...,0hBRqPYPXhr1RkTDG3n4Mk,1.0,1.0,166300.0,0.2140,7ne4VBA60CxGM75vw0EYad,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M,High
3,0.910,112.966,0.670,pop,-4.070,0.304,0.786,Sabrina Carpenter,4.0,0.0634,...,4B4Elma4nNDUyl6D5PvQkj,0.0,0.0,157280.0,0.0939,1d7Ptw3qYcfpdLNL5REhtJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M,High
4,0.783,149.027,0.777,pop,-4.477,0.355,0.939,"ROSÉ, Bruno Mars",4.0,0.2600,...,2IYQwwgxgOIn7t3iF6ufFD,0.0,0.0,169917.0,0.0283,5vNRhkKd0yEAg8suGBpjeY,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M,High

In [6]:
print("Columns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicated rows:", df.duplicated().sum())

df.info()

Columns:
['energy', 'tempo', 'danceability', 'playlist_genre', 'loudness', 'liveness', 'valence', 'track_artist', 'time_signature', 'speechiness', 'track_popularity', 'track_href', 'uri', 'track_album_name', 'playlist_name', 'analysis_url', 'track_id', 'track_name', 'track_album_release_date', 'instrumentalness', 'track_album_id', 'mode', 'key', 'duration_ms', 'acousticness', 'id', 'playlist_subgenre', 'type', 'playlist_id', 'popularity_group']

Missing values:
energy                      1
tempo                       1
danceability                1
playlist_genre              0
loudness                    1
liveness                    1
valence                     1
track_artist                0
time_signature              1
speechiness                 1
track_popularity            0
track_href                  1
uri                         1
track_album_name            1
playlist_name               0
analysis_url                1
track_id                    0
track_name                  0
track_album_release_date    0
instrumentalness            1
track_album_id              0
mode                        1
key                         1
duration_ms                 1
acousticness                1
id                          1
playlist_subgenre           0
type                        1
playlist_id                 0
popularity_group            0
dtype: int64

Duplicated rows: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4831 entries, 0 to 4830
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   energy                    4830 non-null   float64
 1   tempo                     4830 non-null   float64
 2   danceability              4830 non-null   float64
 3   playlist_genre            4831 non-null   object
 4   loudness                  4830 non-null   float64
 5   liveness                  4830 non-null   float64
 6   valence                   4830 non-null   float64
 7   track_artist              4831 non-null   object
 8   time_signature            4830 non-null   float64
 9   speechiness               4830 non-null   float64
 10  track_popularity          4831 non-null   int64
 11  track_href                4830 non-null   object
 12  uri                       4830 non-null   object
 13  track_album_name          4830 non-null   object
 14  playlist_name             4831 non-null   object
 15  analysis_url              4830 non-null   object
 16  track_id                  4831 non-null   object
 17  track_name                4831 non-null   object
 18  track_album_release_date  4831 non-null   object
 19  instrumentalness          4830 non-null   float64
 20  track_album_id            4831 non-null   object
 21  mode                      4830 non-null   float64
 22  key                       4830 non-null   float64
 23  duration_ms               4830 non-null   float64
 24  acousticness              4830 non-null   float64
 25  id                        4830 non-null   object
 26  playlist_subgenre         4831 non-null   object
 27  type                      4830 non-null   object
 28  playlist_id               4831 non-null   object
 29  popularity_group          4831 non-null   object
dtypes: float64(13), int64(1), object(16)
memory usage: 1.1+ MB

In [9]:
drop_cols = [
    "track_href",
    "uri",
    "analysis_url",
    "track_id",
    "track_album_id",
    "playlist_id",
    "id",
    "type"
]

df_clean = df.drop(columns=[col for col in drop_cols if col in df.columns])

df_clean.head()

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,track_album_release_date,instrumentalness,mode,key,duration_ms,acousticness,playlist_subgenre,popularity_group,release_year,duration_min
0,0.592,157.969,0.521,pop,-7.777,0.122,0.535,"Lady Gaga, Bruno Mars",3.0,0.0304,...,2024-08-16,0.0000,0.0,6.0,251668.0,0.3080,mainstream,High,2024.0,4.194467
1,0.507,104.978,0.747,pop,-10.171,0.117,0.438,Billie Eilish,4.0,0.0358,...,2024-05-17,0.0608,1.0,2.0,210373.0,0.2000,mainstream,High,2024.0,3.506217
2,0.808,108.548,0.554,pop,-4.169,0.159,0.372,Gracie Abrams,4.0,0.0368,...,2024-10-18,0.0000,1.0,1.0,166300.0,0.2140,mainstream,High,2024.0,2.771667
3,0.910,112.966,0.670,pop,-4.070,0.304,0.786,Sabrina Carpenter,4.0,0.0634,...,2024-08-23,0.0000,0.0,0.0,157280.0,0.0939,mainstream,High,2024.0,2.621333
4,0.783,149.027,0.777,pop,-4.477,0.355,0.939,"ROSÉ, Bruno Mars",4.0,0.2600,...,2024-10-18,0.0000,0.0,0.0,169917.0,0.0283,mainstream,High,2024.0,2.831950

In [10]:
# Xóa duplicate nếu có
df_clean = df_clean.drop_duplicates()

# Với album name bị thiếu thì điền Unknown
if "track_album_name" in df_clean.columns:
    df_clean["track_album_name"] = df_clean["track_album_name"].fillna("Unknown")

print("Final shape:", df_clean.shape)
print(df_clean.isnull().sum())

Final shape: (4831, 24)
energy                        1
tempo                         1
danceability                  1
playlist_genre                0
loudness                      1
liveness                      1
valence                       1
track_artist                  0
time_signature                1
speechiness                   1
track_popularity              0
track_album_name              0
playlist_name                 0
track_name                    0
track_album_release_date    138
instrumentalness              1
mode                          1
key                           1
duration_ms                   1
acousticness                  1
playlist_subgenre             0
popularity_group              0
release_year                138
duration_min                  1
dtype: int64

In [12]:
df_clean = df_clean.dropna()
print("Final shape:", df_clean.shape)
print(df_clean.isnull().sum())

Final shape: (4692, 24)
energy                      0
tempo                       0
danceability                0
playlist_genre              0
loudness                    0
liveness                    0
valence                     0
track_artist                0
time_signature              0
speechiness                 0
track_popularity            0
track_album_name            0
playlist_name               0
track_name                  0
track_album_release_date    0
instrumentalness            0
mode                        0
key                         0
duration_ms                 0
acousticness                0
playlist_subgenre           0
popularity_group            0
release_year                0
duration_min                0
dtype: int64

In [13]:
output_path = "data/spotify_cleaned.csv"

df_clean.to_csv(output_path, index=False, encoding="utf-8-sig")

print("Saved to:", output_path)

Saved to: data/spotify_cleaned.csv